sudo: false

language: node_js

node_js:
  - 10.14.2

before_install:
  # MongoDb 4.2 docker container
  - docker container run -d -p 27017:27017 mongo:4.2

install:
  - npm install
  - npm install --save-dev ci-toolbox@latest

env:
  global:
    - BUILD_SOUP=true

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  - provider: s3
    on:
      tags: true
      # branch: dblp
    
    # You can refer to environment variables from Travis repo settings!
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    # Name of the S3 bucket to which your site should be uploaded.
    bucket: $AWS_BUCKET
    # Prevent Travis from deleting your built site so it can be uploaded.
    skip_cleanup: true
    # Path of the source directory containing your built site.
    local_dir: deploy
    # Path to a directory containing your built site.
    upload-dir: deploy
    # Set the Cache-Control header.
    cache_control: "max-age=21600"
  # Deploy SOUP list
  - provider: s3
    on:
      tags: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: com.diabeloop.yourloops.doc
    skip_cleanup: true
    local_dir: doc/soup
    upload_dir: soup/message-api
    cache_control: "max-age=21600"

services:
  - docker

before_script:
# Sleeps make me sad, but tests can fail intermittently if mongodb isn't ready.
# See https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
  - sleep 15

script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - npm test
  - npm audit --registry=https://registry.npmjs.org --production --audit-level=moderate
  - ./artifact.sh
