sudo: false

language: node_js

node_js:
  - 0.12.18

install:
  - npm install

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
  artifacts:
    s3_region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /

services:
  - mongodb

before_script:
# Sleeps make me sad, but tests can fail intermittently if mongodb isn't ready
# See https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  - npm test
  - ./artifact.sh

notifications:
  email:
    on_success: change
    on_failure: always
